<a href="https://colab.research.google.com/github/Monalisha-Roy/pytorch/blob/main/practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2. Create a random tensor with shape(7, 7)

In [3]:
import torch

tensor = torch.rand(7, 7)
tensor

tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518],
        [0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208],
        [0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
        [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],
        [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],
        [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839]])

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [4]:
tensor1 = tensor
tensor2 = torch.rand(1, 7)
print(tensor2)

tensor2 = tensor2.T
print(tensor2)

mul = tensor1.matmul(tensor2)
print("Multiplied tensor: ", mul)

tensor([[0.8083, 0.7528, 0.8988, 0.6839, 0.7658, 0.9149, 0.3993]])
tensor([[0.8083],
        [0.7528],
        [0.8988],
        [0.6839],
        [0.7658],
        [0.9149],
        [0.3993]])
Multiplied tensor:  tensor([[1.5166],
        [3.1874],
        [2.5350],
        [2.8343],
        [2.6844],
        [2.6483],
        [2.4059]])


##
4. Set the random seed to 0 and do 2 & 3 over again.

In [5]:
import torch

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

tensor1 = torch.rand(7, 7)
print(tensor1)

tensor2 = torch.rand(1, 7)
print(tensor2)

tensor2 = tensor2.T
print(tensor2)

mul = tensor1.matmul(tensor2)
print(mul, mul.shape)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
tensor([[0.4820],
        [0.8198],
        [0.9971],
        [0.6984],
        [0.5675],
        [0.8352],
        [0.2056]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


## 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [6]:
import torch

if(torch.cuda.is_available()):
  print("Device running on GPU")
  torch.cuda.manual_seed(0)


  t1 = torch.rand(7, 7)
  t2 = torch.rand(1, 7)

  print(t1, t2)

  mul = t1.matmul(t2.T)
  print(mul, mul.shape)
else:
  print("GPU not available")


GPU not available


## 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [8]:
import torch

torch.manual_seed(1234)

if(torch.cuda.is_available()):
  device='cuda'
else:
  device='cpu'

t1 = torch.rand(2, 3)
t2 = torch.rand(2, 3)

t1 = t1.to(device)
t2 = t2.to(device)

t1, t2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [9]:
mul = t1.matmul(t2.T)
print(mul, mul.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


## 8. Find the maximum and minimum values of the output of 7

In [10]:
print("Minimum of t1: ", torch.min(t1))
print("Maximum of t1: ", torch.max(t1))
print("Minimum of t2: ", torch.min(t2))
print("Maximum of t2: ", torch.max(t2))

Minimum of t1:  tensor(0.0290)
Maximum of t1:  tensor(0.7006)
Minimum of t2:  tensor(0.0518)
Maximum of t2:  tensor(0.7837)


## 9. Find the maximum and minimum index values of the output of 7

In [12]:
print("Minimum index values of t1: ", torch.argmin(t1))
print("Maximum index values of t1: ", torch.argmax(t1))
print("Minimum index values of t2: ", torch.argmin(t2))
print("Maximum index values of t2: ", torch.argmax(t2))

Minimum index values of t1:  tensor(0)
Maximum index values of t1:  tensor(5)
Minimum index values of t2:  tensor(0)
Maximum index values of t2:  tensor(4)


## 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [19]:
import torch

tensor = torch.rand(1, 1, 1, 10)
print(tensor, tensor.shape)

squeezed_tensor = tensor.squeeze()
squeezed_tensor, squeezed_tensor.shape

tensor([[[[0.6604, 0.1303, 0.3498, 0.3824, 0.8043, 0.3186, 0.2908, 0.4196,
           0.3728, 0.3769]]]]) torch.Size([1, 1, 1, 10])


(tensor([0.6604, 0.1303, 0.3498, 0.3824, 0.8043, 0.3186, 0.2908, 0.4196, 0.3728,
         0.3769]),
 torch.Size([10]))