<a href="https://colab.research.google.com/github/Monalisha-Roy/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
## Creating Tensors in Range
range = torch.range(1, 10)
print(range)
one_to_ten = torch.range(start=0, end=1000, step=77)
one_to_ten

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


<ipython-input-2-b888bb1af784>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(1, 10)
<ipython-input-2-b888bb1af784>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start=0, end=1000, step=77)


tensor([  0.,  77., 154., 231., 308., 385., 462., 539., 616., 693., 770., 847.,
        924.])

In [3]:
# Creating tesnors like
ten_zeros = torch.zeros_like(input=range)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
## Tensor DAtatypes

## Tensor Datatypes
NOte: Tensor datatypes is one of the 3 big errors you'
ll run into with PyTorch & deep learning
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

In [5]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 5.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your Tensor on
                               requires_grad=False # whether or not to track gradients with this tensors operations
                               )
float_32_tensor


tensor([3., 6., 5.])

In [6]:
float_32_tensor.dtype

torch.float32

In [7]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 5.], dtype=torch.float16)

In [14]:
mul = float_16_tensor * float_32_tensor
print(mul)
print(f"float_16_tensor: {float_16_tensor}")
print(f"float_32_tensor: {float_32_tensor}")

tensor([ 9., 36., 25.])
float_16_tensor: tensor([3., 6., 5.], dtype=torch.float16)
float_32_tensor: tensor([3., 6., 5.])


In [17]:
int_32_tensor = torch.tensor([3, 6, 7], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 7])

In [18]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 35.])

### Getting information from tensors ( Tensor attributes )

1. tensors not right datatype - to do get datatype from a tensor , can use tensor.dtype
2. tensors not right shape - to get shape from a tensor, can use tensor.device
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [20]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1192, 0.2948, 0.8047, 0.4965],
        [0.8565, 0.7451, 0.7806, 0.9454],
        [0.8663, 0.3080, 0.1778, 0.1868]])

In [21]:
# find details of some_tensor
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1192, 0.2948, 0.8047, 0.4965],
        [0.8565, 0.7451, 0.7806, 0.9454],
        [0.8663, 0.3080, 0.1778, 0.1868]])
datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element wise)
* Division
* Matrix Multiplication

In [31]:
# Create tensor and add 32 to it
tensor = torch.tensor([1, 2, 3])
tensor + 32

tensor([33, 34, 35])

In [32]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [33]:
tensor

tensor([1, 2, 3])

In [34]:
# subtracting by 10
tensor - 10

tensor([-9, -8, -7])

In [35]:
# try out tensor built in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
# division
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

## Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning.

1. Element-wise multiplication
2. Matrix multiplication(dot product)

In [37]:
# Element vise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [38]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [39]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [57]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
# Find the min
torch.min(x), x.max()

(tensor(1), tensor(91))

In [59]:
# Find the max
torch.max(x), x.min()

(tensor(91), tensor(1))

In [60]:
# find the mean - note: teh torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [61]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [62]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [63]:
# find the position in tensor that has the minimum value with argmin() -> return the index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [64]:
x[0]

tensor(1)

In [65]:
# find the position in tensor that has the maximum value with argmax
x.argmax()

tensor(9)

In [67]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

1. Reshaping - reshape an input tensor to a defined shape
2. view - return a view of a input tensor of certain shape but keep the same memory as teh original tensor
3. stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
4. Squeeze - removes all '1' dimensions from a tensor
5. Unsqueeze - add a 1 dimension to a target tensor
6. Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [76]:
# lets create a tensor
import torch
x = torch.arange(0., 10.)
x, x.shape

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([10]))

In [96]:
# add an extra dimension
# RESHAPE
x_reshaped = x.reshape(1, 10)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(10, 1)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(2, 5)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(5, 2)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(1, 10)
print(x_reshaped, x_reshaped.shape)

tensor([[7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 10])
tensor([[7.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([10, 1])
tensor([[7., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]) torch.Size([2, 5])
tensor([[7., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]]) torch.Size([5, 2])
tensor([[7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 10])


In [97]:
# change the view
z = x.view(1, 10)
z, z.shape

(tensor([[7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]))

In [98]:
# VIEW
# changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[0, 0] = 7
z, x

(tensor([[7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [99]:
# STACK
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # vstack
print(x_stacked)

x_stacked = torch.stack([x,x,x,x], dim=1) # hstack
print(x_stacked)

tensor([[7., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[7., 7., 7., 7.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [103]:
# SQUEEZE
# torch.sqeeze() - removes all 1 dimensions from the tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove xtra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([7., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([10])


In [107]:
# UNSQUEEZE
# torch.unsqeeze() - adds a single dimensions to a target tensor at a specific dimension
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# adds an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([7., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([10])

New tensor: tensor([[7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 10])


In [111]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) #{height, width, colour_channels}

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->3

print(f"Previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])
