<a href="https://colab.research.google.com/github/Monalisha-Roy/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import numpy as np

In [6]:
# Tensor initialization directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [46]:
# Tensor initialization from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
# Tensors from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5448, 0.8032],
        [0.3916, 0.5742]]) 



In [9]:
# Tensors with random or constant values
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch .zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor \n {ones_tensor} \n")
print(f"Zeros Tensor \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.1678, 0.0296, 0.6336],
        [0.7948, 0.1901, 0.3299]]) 

Ones Tensor 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [10]:
# Tensor Attributes
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
# Tensor Operations
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [19]:
rand_tenosr = torch.rand(3,4)
rand_tensor
torch.is_tensor(rand_tensor)

True

In [20]:
storage = rand_tensor.storage()
print(torch.is_storage(storage))

True


<ipython-input-20-70c0d7dfac1a>:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = rand_tensor.storage()


In [23]:
# standard numpy-like indexing and slicing
tensor = torch.ones(4, 4)
print(tensor)
tensor[:,1] = 0
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [28]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # dim=1 for columns
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=0) # dim=0 for rows
t2

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [32]:
tensor = torch.tensor([[2, 3, 4], [4, 2, 1]])
print(tensor)

# this computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

# alternative syntax
print(f"tensor * tensor \n {tensor * tensor}")

tensor([[2, 3, 4],
        [4, 2, 1]])
tensor.mul(tensor) 
 tensor([[ 4,  9, 16],
        [16,  4,  1]]) 

tensor * tensor 
 tensor([[ 4,  9, 16],
        [16,  4,  1]])


In [34]:
# matrix multiplication between two tensors
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)}")
# alternative syntax
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[29, 18],
        [18, 21]])
tensor @ tensor.T 
 tensor([[29, 18],
        [18, 21]])


In [35]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[2, 3, 4],
        [4, 2, 1]]) 

tensor([[7, 8, 9],
        [9, 7, 6]])


In [36]:
# Bridge with Numpy
# Tensor to Numpy array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
print(f"t datatype: {t.dtype}")
print(f"n datatype: {n.dtype}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t datatype: torch.float32
n datatype: float32


In [38]:
# A change in tensor affects Numpy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


In [42]:
# Numpy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n: {n}")
print(f"t: {t}")
print(f"dtype of n: {n.dtype}")
print(f"dtype of t: {t.dtype}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
dtype of n: float64
dtype of t: torch.float64


In [45]:
# changes in Numpy array reflects in Tensor
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([5., 5., 5., 5., 5.], dtype=torch.float64)
n: [5. 5. 5. 5. 5.]
