<a href="https://colab.research.google.com/github/Monalisha-Roy/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

In [5]:
## Creating Tensors in Range
range = torch.range(1, 10)
print(range)
one_to_ten = torch.range(start=0, end=1000, step=77)
one_to_ten

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


<ipython-input-5-b888bb1af784>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(1, 10)
<ipython-input-5-b888bb1af784>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start=0, end=1000, step=77)


tensor([  0.,  77., 154., 231., 308., 385., 462., 539., 616., 693., 770., 847.,
        924.])

In [6]:
# Creating tesnors like
ten_zeros = torch.zeros_like(input=range)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
## Tensor DAtatypes

## Tensor Datatypes
NOte: Tensor datatypes is one of the 3 big errors you'
ll run into with PyTorch & deep learning
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

In [8]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 5.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your Tensor on
                               requires_grad=False # whether or not to track gradients with this tensors operations
                               )
float_32_tensor


tensor([3., 6., 5.])

In [9]:
float_32_tensor.dtype

torch.float32

In [10]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 5.], dtype=torch.float16)

In [11]:
mul = float_16_tensor * float_32_tensor
print(mul)
print(f"float_16_tensor: {float_16_tensor}")
print(f"float_32_tensor: {float_32_tensor}")

tensor([ 9., 36., 25.])
float_16_tensor: tensor([3., 6., 5.], dtype=torch.float16)
float_32_tensor: tensor([3., 6., 5.])


In [12]:
int_32_tensor = torch.tensor([3, 6, 7], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 7])

In [13]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 35.])

### Getting information from tensors ( Tensor attributes )

1. tensors not right datatype - to do get datatype from a tensor , can use tensor.dtype
2. tensors not right shape - to get shape from a tensor, can use tensor.device
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [14]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2392, 0.8962, 0.8921, 0.7943],
        [0.7745, 0.6641, 0.2843, 0.9016],
        [0.5120, 0.5731, 0.0635, 0.3774]])

In [15]:
# find details of some_tensor
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2392, 0.8962, 0.8921, 0.7943],
        [0.7745, 0.6641, 0.2843, 0.9016],
        [0.5120, 0.5731, 0.0635, 0.3774]])
datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element wise)
* Division
* Matrix Multiplication

In [16]:
# Create tensor and add 32 to it
tensor = torch.tensor([1, 2, 3])
tensor + 32

tensor([33, 34, 35])

In [17]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [18]:
tensor

tensor([1, 2, 3])

In [19]:
# subtracting by 10
tensor - 10

tensor([-9, -8, -7])

In [20]:
# try out tensor built in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [21]:
# division
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

## Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning.

1. Element-wise multiplication
2. Matrix multiplication(dot product)

In [22]:
# Element vise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [23]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [24]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [25]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [26]:
# Find the min
torch.min(x), x.max()

(tensor(1), tensor(91))

In [27]:
# Find the max
torch.max(x), x.min()

(tensor(91), tensor(1))

In [28]:
# find the mean - note: teh torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [29]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [30]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [31]:
# find the position in tensor that has the minimum value with argmin() -> return the index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [32]:
x[0]

tensor(1)

In [33]:
# find the position in tensor that has the maximum value with argmax
x.argmax()

tensor(9)

In [34]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

1. Reshaping - reshape an input tensor to a defined shape
2. view - return a view of a input tensor of certain shape but keep the same memory as teh original tensor
3. stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
4. Squeeze - removes all '1' dimensions from a tensor
5. Unsqueeze - add a 1 dimension to a target tensor
6. Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [35]:
# lets create a tensor
import torch
x = torch.arange(0., 10.)
x, x.shape

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([10]))

In [36]:
# add an extra dimension
# RESHAPE
x_reshaped = x.reshape(1, 10)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(10, 1)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(2, 5)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(5, 2)
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(1, 10)
print(x_reshaped, x_reshaped.shape)

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 10])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([10, 1])
tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]) torch.Size([2, 5])
tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]]) torch.Size([5, 2])
tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 10])


In [37]:
# change the view
z = x.view(1, 10)
z, z.shape

(tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]))

In [38]:
# VIEW
# changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[0, 0] = 7
z, x

(tensor([[7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [39]:
# STACK
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # vstack
print(x_stacked)

x_stacked = torch.stack([x,x,x,x], dim=1) # hstack
print(x_stacked)

tensor([[7., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[7., 7., 7., 7.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [40]:
# SQUEEZE
# torch.sqeeze() - removes all 1 dimensions from the tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove xtra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([7., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([10])


In [41]:
# UNSQUEEZE
# torch.unsqeeze() - adds a single dimensions to a target tensor at a specific dimension
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# adds an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([7., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([10])

New tensor: tensor([[7., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 10])


In [42]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) #{height, width, colour_channels}

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->3

print(f"Previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [43]:
x_original[0,0,0] = 5433320
x_original[0,0,0], x_permuted[0,0,0]

(tensor(5433320.), tensor(5433320.))

## INDEXING (selecting data from tensors)

INdexing with pytorch is similar to indexing with Numpy

In [44]:
# create a tensor
x = torch.arange(1, 19).reshape(2, 3, 3)
print(x, x.shape)

print("\n")
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x, x.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]) torch.Size([2, 3, 3])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [45]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [46]:
# let's index on the mdidle bracket (dim=1)
x[0,0], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [47]:
# lets index on most inner bracket
x[0][0][1], x[0][1][2], x[0, 2, 2]

(tensor(2), tensor(6), tensor(9))

In [48]:
# you can also use ':' to select 'all' of  a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [49]:
# get all values of 0th and 1st  dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [50]:
# get all values of the 0 dimension but only the 1 index value of teh 1st and 2nd dimension
x[:, 1, 1], x[0, 1, 1]

(tensor([5]), tensor(5))

In [51]:
# get index 0 of 0th and 1st dimension and all values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [52]:
# index on x to return 9
print(x[0, 2, 2])

# index on x to return 3, 6, 9
print(x[0, :, 2])

tensor(9)
tensor([3, 6, 9])


## Pytorch and Numpy

Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data is NumPy, wnat in PyTorch tensor -> 'torch.from_numpy(ndarray)
* PyTorch tensor-> NumPy -> torch.Tensor.numpy()

In [53]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy->pytorch, pythorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [54]:
array.dtype

dtype('float64')

In [55]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [56]:
# change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [57]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [58]:
numpy_tensor.dtype

dtype('float32')

In [59]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

'start with random numbers -> tensor oerations -> update random numbers to try and make them of the data -> again -> again.......

To reduce the randomness in neural networks and PyTorch comes the concept of a rnadom seed.

Essentially what the random seed does is 'flavour' the randomness.

In [60]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8034, 0.7301, 0.8436, 0.4210],
        [0.7679, 0.6912, 0.4142, 0.1248],
        [0.5038, 0.8044, 0.8630, 0.5733]])
tensor([[0.1746, 0.0167, 0.3188, 0.2416],
        [0.7244, 0.6021, 0.1156, 0.6421],
        [0.9512, 0.2527, 0.4608, 0.5865]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [61]:
# Let's make some random but reproducible tensors

import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on teh GPUs (and making faster computations)

GPUs  = faster computation on numbers, thanks to cuda + NIVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(good)

In [62]:
!nvidia-smi

Fri Dec 20 06:36:22 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [63]:
# check for GPU access with pytorch.

import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on teh GPU or CPU, it's best practice to setup device agnostic code:

eg: run on GPU if available, else default to CPU

In [64]:
## SEt up device agnostic code
device   = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [65]:
# count the number of GPU
torch.cuda.device_count()

1

## Putting Tensors (and models ) on teh GPU

The reason we want out tensors/models on teh GPU is because using a GPU results in faster computations.

In [66]:
# Create a tensor (default on teh CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [67]:
# Move tensro to GPU ( if availavle )
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

### MOving tensors back to the cpu

In [68]:
# If tensro is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [69]:
# To fix the GPU  with NumPy issue, we can first set i tto the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])